models/images.py
from extensions import db


class Image(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    image_url = db.Column(db.String(200), nullable=False)
    approved = db.Column(db.Boolean, default=False)

    def __repr__(self):
        return f"<Image {self.image_url}>"

camera/views.py
from extensions import db
from models.images import Image
from flask_login import login_required
from camera.utils import upload_image_to_cloudinary
from flask import Blueprint, render_template, request, jsonify, flash, redirect, url_for

bp = Blueprint("camera", __name__)


@bp.route("/selfie/", methods=["GET"])
def selfie():
    return render_template("webcam.html")


@bp.route("/selfie/upload_selfie/", methods=["POST"])
def upload_selfie():
    try:
        image_data = request.form.get("image_data")

        upload = upload_image_to_cloudinary(image_data)

        image = Image(image_url=upload["secure_url"])

        try:
            db.session.add(image)

        except Exception as e:
            raise Exception(str(e))

        else:
            db.session.commit()

            return jsonify({"message": "Image uploaded successfully!"})

    except Exception as e:
        return jsonify({"error": str(e)}), 500


@bp.route("/success/", methods=["GET"])
def success():
    return render_template("success.html")


@login_required
@bp.route("/images/image_actions/", methods=["POST"])
def image_actions():
    data = request.json
    
    selected_action = data.get("action")
    selected_images = data.get("images")

    if selected_action == "delete":
        for id in selected_images:
            image = Image.query.get(int(id))
            
            print(image)

            try:
                db.session.delete(image)
                db.session.commit()

            except Exception as e:
                flash("Something went wrong.", "error")

    elif selected_action == "approve":
        for id in selected_images:
            image = Image.query.get(int(id))
            
            print(image)

            image.approved = True

            try:
                db.session.commit()

            except Exception as e:
                flash("Something went wrong.", "error")

    elif selected_action == "disapprove":
        for id in selected_images:
            image = Image.query.get(int(id))
            
            print(image)

            image.approved = False

            try:
                db.session.commit()

            except Exception as e:
                flash("Something went wrong.", "error")

    return jsonify({"message": "Action performed successfully"})


@login_required
@bp.route("/images/", methods=["GET"])
def images():
    all_images = Image.query.all()

    return render_template("images.html", images=all_images)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='favicon.png') }}"
      type="image/x-icon"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/app.css') }}"
    />
    <title>ASAR | {% block title %} {% endblock %}</title>
  </head>
  <body>
    <!-- content -->
    <div class="content">{% block content %} {% endblock %}</div>
    <!-- content -->

    <!-- footer -->
    <footer class="container-fluid pt-3 border-top border-dark-subtle">
      <div class="d-flex justify-content-center align-items-center">
        <p class="mx-1 fw-bold text-small">
          <i class="bi bi-c-circle"></i> 2023 - ASAR | Developed by
          <a href="https://dafterinc.com" target="_blank">Dafter Inc.</a>
        </p>
      </div>
    </footer>
    <!-- footer -->

    <!-- script -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    <!-- script -->
  </body>
</html>

templates/images.html
{% extends 'base.html' %}

<!-- title -->

{% block title %} Images {% endblock %}

<!-- title -->

<!-- content -->

{% block content %}
<!--  -->

<div class="my-3">
  <h4 class="text-center">All Images</h4>
  <br />
  {% if images %}
  <!--  -->
  <div class="all-images">
    {% for image in images %}
    <!--  -->
    {% if image.approved %}
    <div class="approved-img mb-3 py-3 rounded">
      <img
        src="{{ image.image_url }}"
        alt="Image {{ image.id }}"
        class="mx-2 mb-3 img-fluid rounded"
        id="display-img"
      />
      <div class="form-check">
        <input
          class="form-check-input"
          type="checkbox"
          value="{{ image.id }}"
          id="checkbox_{{ image.id }}"
        />
        <label class="form-check-label mt-1" for="checkbox_{{ image.id }}">
          Image: id_{{ image.id }}
        </label>
      </div>
    </div>
    {% else %}
    <div class="non-approved-img mb-3 py-3 rounded">
      <img
        src="{{ image.image_url }}"
        alt="Image {{ image.id }}"
        class="mx-2 mb-3 img-fluid rounded"
        id="display-img"
      />
      <div class="form-check">
        <input
          class="form-check-input"
          type="checkbox"
          value="{{ image.id }}"
          id="checkbox_{{ image.id }}"
        />
        <label class="form-check-label mt-1" for="checkbox_{{ image.id }}">
          Image: id_{{ image.id }}
        </label>
      </div>
    </div>
    {% endif %}
    <!--  -->
    {% endfor %}
  </div>
  <!--  -->
  {% else %}
  <!--  -->
  <h2 class="mt-5 text-center">No images have been uploaded.</h2>
  <!--  -->
  {% endif %}
</div>

<div id="img-action">
  <select
    id="action-select"
    name="action"
    class="form-select"
    aria-label="Action to perform on image"
  >
    <option class="bg-success-subtle" value="approve">Approve</option>
    <option class="bg-warning-subtle" value="disapprove">Disapprove</option>
    <option class="bg-danger-subtle" value="delete">Delete</option>
  </select>
  <button
    class="btn btn-sm btn-primary"
    type="button"
    id="perform-action-button"
  >
    Perform Action
  </button>
</div>

<script src="{{ url_for('static', filename='js/images.js') }}"></script>

<!--  -->
{% endblock %}

<!-- content -->

templates/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
<div class="col text-center mx-auto">
  <img id="World Environment Day" src="{{ url_for('static', filename='img/hero.png') }}" alt="#CleanAirForBlueSkies by Asar" width="100%" />
  <h1 class="p-2">The International Day of <span class="color-primary">Clean Air</span> for <span class="color-primary">Blue Skies</span></h1>
  <h2 class="color-primary px-1 mb-4">#CleanAirForBlueSkies</h2>
  <p class="text-center mb-3 px-1">Did you know?</p>
  <div class="d-flex">
    <ul class="text-start mx-auto px-4 fw-bold">
      <li>Air pollution is India's 2nd largest problem after malnutrition.</li>
      <li>It is a pan-India problem, with over 100 cities in India designated as Non- Attainment cities.</li>
      <li>Air pollution accounts for an estimated 12.5% of deaths in India.</li>
      <li>Inhaling air pollution decreases the average human lifespan by 1 to 2 years.</li>
      <li>Beijing's air pollution has given rise to a new disease, called the Beijing cough.</li>
    </ul>
  </div>
  <p class="text-center mt-3 mb-4 px-1">It's time we brought change.</p>
  <p class="text-center mb-3 px-1 fw-bold">This <span class="color-primary">07/09/2023</span>, Join our campaign to achieve <span class="color-primary">blue</span> skies 365 days of the year.</p>
  <div class="d-flex">
    <ul class="text-start mx-auto px-4 fw-bold">
      <li>Click the link below to take a selfie (Make sure you're in a bright, well lit area)</li>
      <li>Position the camera so that the hashtag <span class="color-primary">#ISupportCleanAirForBlueSkies</span> is across your chest</li>
      <li>Point to the hashtag and smile so we can see your 3000 watt smile!</li>
      <li>Click the picture, approve the picture and hit send.</li>
    </ul>
  </div>
  <p class="text-center m-4 px-1">From the 1st of September, your picture will join our photowall to show the number of people who pledge to work for clean air and blue skies.</p>
  <p class="text-center mb-3 px-1 fst-italic">Spread the word, since we don't spread air pollution!</p>
  <div>
    <a class="btn bg-green btn-lg" href="{{ url_for('camera.selfie') }}" role="button">
      <div class="container-fluid mb-0">
        <p class="text-center text-caption text-white fw-bold mb-1">Pledge Your Support By</p>
        <h4 class="text-center text-black"><i class="bi bi-camera-fill"></i> Taking a Selfie!</h4>
      </div>
    </a>
  </div>
</div>

<hr class="my-4 divider" />

{% if length %}
<p class="mb-4 text-center"><span class="text-danger"><strong><ins>{{ length }}</ins></strong></span> people have already pledged their support.</p>
{% endif %}

{% if images %}
<div class="container px-1 mx-auto mb-3">
  <div class="row row-cols-2 row-cols-md-4 g-1">
    {% for image in images %}
      {% if image.approved %}
        <div class="col">
          <img src="{{ image.image_url }}" alt="Image {{ image.id }}" class="img-fluid img-thumbnail mx-auto" id="display-img" />
        </div>
      {% endif %}
    {% endfor %}
  </div>
</div>
{% endif %}
{% endblock %}

templates/notifications.html
<!-- flask messages -->
{% with messages = get_flashed_messages(with_categories=true) %}
<!--  -->
{% if messages %}
<!--  -->
{% for category, message in messages %}
<!--  -->
{% if category == 'message' %}
<div
  class="alert alert-success alert-dismissible fade show shadow"
  role="alert"
  id="flash-box"
>
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
    onclick="clearNotification()"
  ></button>
  {{ message }}
</div>
{% elif category == 'info' %}
<div
  class="alert alert-info alert-dismissible fade show shadow"
  role="alert"
  id="flash-box"
>
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
    onclick="clearNotification()"
  ></button>
  {{ message }}
</div>
{% elif category == 'warning' %}
<div
  class="alert alert-warning alert-dismissible fade show shadow"
  role="alert"
  id="flash-box"
>
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
    onclick="clearNotification()"
  ></button>
  {{ message }}
</div>
{% elif category == 'error' %}
<div
  class="alert alert-danger alert-dismissible fade show shadow"
  role="alert"
  id="flash-box"
>
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
    onclick="clearNotification()"
  ></button>
  {{ message }}
</div>
{% endif %}
<!--  -->
{% endfor %}
<!--  -->
{% endif %}
<!--  -->
{% endwith %}
<!-- flask messages -->

templates/success.html
{% extends 'base.html' %}

<!-- title -->

{% block title %} Success {% endblock %}

<!-- title -->

<!-- content -->

{% block content %}
<!--  -->

<div class="container backdrop pt-3 col text-center">
  <img
    class="text-center"
    id="World Environment Day"
    src="{{ url_for('static', filename='logo/asar-wed.png') }}"
    alt="World Environment Day Campaign by Asar"
  />
  <h1 class="text-center color-vivid-malachite">Thank you for your support!</h1>
  <p class="text-center black mb-3">
    Share the QR code or share link via social media
  </p>
  <br />
  <img
    class="text-center mb-3"
    id="QRCode"
    src="{{ url_for('static', filename='logo/qr.png') }}"
    alt="Scan this QR Code"
  />
  <br />
  <br />
  <div class="share-buttons">
    <button class="share-button facebook">
      <i class="bi bi-facebook"></i>
    </button>
    <button class="share-button twitter">
      <i class="bi bi-twitter"></i>
    </button>
    <button class="share-button linkedin">
      <i class="bi bi-linkedin"></i>
    </button>
    <button class="share-button pinterest">
      <i class="bi bi-pinterest"></i>
    </button>
    <button class="share-button reddit">
      <i class="bi bi-reddit"></i>
    </button>
    <button class="share-button whatsapp">
      <i class="bi bi-whatsapp"></i>
    </button>
  </div>
</div>

<script src="{{ url_for('static', filename='js/share.js') }}"></script>

<!--  -->
{% endblock %}

<!-- content -->

templates/webcam.html
{% extends 'base.html' %}

<!-- title -->

{% block title %} Selfie {% endblock %}

<!-- title -->

<!-- content -->

{% block content %}

<div class="d-flex justify-content-center align-items-center flex-column">
  <br />
  <div id="webcam-container">
    <div id="video-container" class="view-box">
      <video
        id="video"
        class="img-fluid img-thumbnail rounded"
        autoplay
      ></video>
      <canvas
        id="canvas"
        class="img-fluid img-thumbnail rounded"
        style="display: none"
      ></canvas>
      <img
        id="watermark"
        src="{{ url_for('static', filename='logo/asar-badge.png') }}"
        alt="Watermark"
      />
    </div>
    <br />
    <button id="capture-btn" type="button" class="btn btn-lg bg-green w-100">
      <i class="bi bi-camera"></i> Take a selfie!
    </button>
    <br />
  </div>

  <br />
  <!-- Request Camera Access Manually -->
  <button
    id="camera-access-btn"
    type="button"
    class="btn btn-outline-info btn-sm"
    style="display: none"
  >
    <i class="bi bi-camera"></i> Allow Camera Access
  </button>

  <div id="preview-container" style="display: none">
    <!-- Preview image -->
    <div class="view-box">
      <img
        id="preview"
        style="display: none"
        class="img-fluid img-thumbnail rounded"
      />
      <span class="loader" id="spinner"></span>
    </div>
    <br />
    <!-- Retake and upload buttons -->
    <button
      id="retake-btn"
      type="button"
      class="btn btn-lg btn-warning w-100"
      style="display: none"
    >
      <i class="bi bi-arrow-repeat"></i> Retake
    </button>
    <br />
    <button
      id="upload-btn"
      type="button"
      class="btn btn-lg btn-success w-100"
      style="display: none"
    >
      <i class="bi bi-upload"></i> Upload
    </button>
    <br />
  </div>
</div>

<script src="{{ url_for('static', filename='js/webcam.js') }}"></script>

{% endblock %}

<!-- content -->